config/routes.rb
Rails.application.routes.draw do
  root   'radio_stations#top'

  get    '/signup',   to: 'users#new'

  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  delete '/signout',  to: 'sessions#destroy'

  resources :radio_stations do
    collection do
      post :confirm
    end
  end

  resources :users, except: [:index, :new] do
    collection do
      post :confirm
    end
    resources :favorite_stations, only: [:index]
  end

  resources :favorites, only: %i[ create destroy ]

  resources :account_activations, only: [:edit]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/favorite_stations_controller.rb
class FavoriteStationsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @favorite_stations = @user.favorite_stations
  end
end

app/views/favorite_stations/index.html.erb
<% content_for :html_title, "#{@user.name}'s Favorite radio stations" %>
<section class="probootstrap-section">
  <div class="container">

    <div class="row mb-4 pt-5">
      <div class="col-md-4">
        <h2 class="h1 mb-0 mt-0">Favorite Radio Stations</h2>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-6">
        <p class="lead"><%= @user.name %>'s Favorite Radio Stations.</p>
        <p class="notice"><%= notice %></p>
      </div>
    </div>

    <div class="row blog-grid">
    <!-- loop for radio_stations -->
    <% @favorite_stations.each do |radio_station| %>
      <div class="col-lg-4 col-md-6">
        <div class="course-box">
          <div class="course-details">
            <h4><%= link_to radio_station.callsign, radio_station.webcast_url,
                  rel: 'noopener', target: '_blank' %></h4>
            <p><%= radio_station.comment %></p>
          </div><!-- end course-details -->
          <div class="course-footer clearfix">
            <div class="pull-left">
              <ul class="list-inline">
                <li>
                  <a href="<%= user_path(radio_station.user.id) %>">
                    <i class="fa fa-user"></i> <%= radio_station.user.name %></a>
                </li>
                <li>
                  <a href="<%= radio_station_path(radio_station.id) %>">
                    <i class="fa fa-clock-o"></i> <%= radio_station.updated_at %></a>
                </li>
                <% if @user == current_user %>
                <li><%= link_to 'Delete', favorite_path(id: radio_station.id),
                      method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
                <% end %>
              </ul>
            </div><!-- end pull-left -->
          </div><!-- end course-footer -->
        </div><!-- end course-box -->
      </div>
    <% end %>
    <!-- loop for radio_stations -->
    </div>

  </div>
</section>