config/routes.rb
Rails.application.routes.draw do
  root   'radio_stations#top'

  get    '/signup',   to: 'users#new'

  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  delete '/signout',  to: 'sessions#destroy'

  resources :radio_stations do
    collection do
      post :confirm
    end
  end

  resources :users, except: [:index, :new] do
    collection do
      post :confirm
    end
    resources :favorite_stations, only: [:index]
  end

  resources :favorites, only: %i[ create destroy ]

  resources :account_activations, only: [:edit]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :activation_token
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 30 }
  validates(
    :email,
    presence: true,
    length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: { case_sensitive: false }
  )
  before_save { email.downcase! }
  has_secure_password
  validates(
    :password,
    presence: true,
    length: { minimum: 6 },
    allow_nil: true
  )
  has_many :radio_stations, dependent: :destroy
  has_many :favorites, -> { order(:id) }, dependent: :destroy
  has_many :favorite_stations, through: :favorites, source: :radio_station

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :signed_in_user, only: %i[ edit show destroy ]

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def confirm
    @user = User.new(user_params)
    render :new if @user.invalid?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      NotifyMailer.notify_mail(@user).deliver
      redirect_to(
        root_path,
        notice: "Please check your email to activate your account."
      )
    else
      redirect_to root_path, notice: "Error..."
    end
  end

  def show
  end

  def edit
    unless @user.id.eql?(current_user.id)
      redirect_to root_path, notice: "Invalid User!"
    end
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: "User info was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if @user.id.eql?(current_user.id)
      session.delete(:user_id)
      ResetCallsignService.call(@user)
      @user.destroy
      redirect_to root_path, notice: "You are not registered as a user."
    else
      redirect_to root_path, notice: "Invalid User!"
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_dialog.html.erb
<div class="modal fade show" tabindex="-1" role="dialog" style="padding-right: 15px; display: block;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
<div class="modal-backdrop fade show"></div>

app/views/users/_dialog_confirm.html.erb
<%= render partial: 'users/form_confirm', layout: 'users/dialog', locals: {user: user} %>

app/views/users/_dialog_edit.html.erb
<%= render partial: 'users/form_edit', layout: 'users/dialog', locals: {user: user} %>

app/views/users/_dialog_new.html.erb
<%= render partial: 'users/form_new', layout: 'users/dialog', locals: {user: user} %>

app/views/users/_form_confirm.html.erb
<% content_for :html_title, "Register your account" %>
<div class="card card-register mx-auto mt-5">
  <div class="card-header">Register an Account</div>

  <div class="card-body">
    <!-- form -->
    <%= form_with(model: user, url: users_path, local: true) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :password %>
      <%= f.hidden_field :password_confirmation %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <p><%= user.name %></p>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email address' %>
        <p><%= user.email %></p>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <p><%= user.password %></p>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary btn-block' %>
    <% end %>
    <!--/form -->

    <div class="text-center">
      <%= form_with(
        model: user, url: signup_path, local: true, method: 'get'
      ) do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :password %>
        <%= f.hidden_field :password_confirmation %>
        <%= f.submit "Back", name: 'back',
          class: 'btn btn-block d-block small mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form_edit.html.erb
<% content_for :html_title, "Edit your profile/#{@user.name}" %>
<div class="card card-register mx-auto mt-5">
  <div class="card-header">Editing Your Profile</div>

  <div class="card-body">
    <!-- form -->
    <%= form_with(model: user, url: user_path, local: true) do |f| %>
      <% if user.errors.any? %>
      <div id="error_explanation">
        <h6><%= pluralize(user.errors.count, "error") %>:</h6>
        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, aria: {describedby: 'nameHelp'},
          placeholder: "Enter name", class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email address' %>
        <%= f.email_field :email, aria: {describedby: 'emailHelp'},
          placeholder: "Enter email", class: 'form-control' %>
      </div>
      <%= f.submit "Update", class: 'btn btn-primary btn-block' %>
    <% end %>
    <!--/form -->

    <div class="text-center">
      <%= link_to "Cancel", root_path, class: 'd-block small mt-3' %>
    </div>
  </div>
</div>

app/views/users/_form_new.html.erb
<% content_for :html_title, "Sign up" %>
<div class="card card-register mx-auto mt-5">
  <div class="card-header">Sign Up</div>

  <div class="card-body">
    <!-- form -->
    <%= form_with(model: user, url: confirm_users_path, local: true) do |f| %>
      <% if user.errors.any? %>
      <div id="error_explanation">
        <h6><%= pluralize(user.errors.count, "error") %>:</h6>
        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, aria: {describedby: 'nameHelp'},
          placeholder: "Enter name", class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email address' %>
        <%= f.email_field :email, aria: {describedby: 'emailHelp'},
          placeholder: "Enter email", class: 'form-control' %>
      </div>
      <div class="form-group">
        <div class="form-row">
          <div class="col-md-6">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password,
              placeholder: "Password", class: 'form-control' %>
          </div>
          <div class="col-md-6">
            <%= f.label :password_confirmation, 'Confirm password' %>
            <%= f.password_field :password_confirmation,
              placeholder: "Confirm password", class: 'form-control' %>
          </div>
        </div>
      </div>
      <%= f.submit "Register", class: 'btn btn-primary btn-block' %>
    <% end %>
    <!--/form -->

    <div class="text-center">
      <%= link_to "Cancel", root_path, class: 'd-block small mt-3' %>
    </div>
  </div>
</div>

app/views/users/confirm.html.erb
<%= render partial: 'users/dialog_confirm', layout: 'radio_stations/layout', locals: {user: @user} %>

app/views/users/edit.html.erb
<%= render partial: 'users/dialog_edit', layout: 'radio_stations/layout', locals: {user: @user} %>

app/views/users/new.html.erb
<%= render partial: 'users/dialog_new', layout: 'radio_stations/layout', locals: {user: @user} %>

app/views/users/show.html.erb
<% content_for :html_title, "#{@user.name}" %>
<section class="bg-light" id="team">
  <div class="container">

    <div class="row">
      <div class="col-sm-4"></div>

      <div class="col-sm-4">
        <div class="team-member">
          <h5><%= @user.name %></h5>
          <p class="text-muted">Email: <%= @user.email %></p>
          <ul class="list-inline">
            <li class="list-inline-item">
              <%= link_to "Edit your profile",
                edit_user_path(user_id: @user.id),
                class: 'btn-default' %>
            </li>
            <li class="list-inline-item">
              <%= link_to "My Favorite Stations",
                user_favorite_stations_path(user_id: @user.id),
                class: 'btn-default' %>
            </li>
            <li class="list-inline-item">
              <%= link_to "Erase user registration",
                user_path(user_id: @user.id),
                class: 'btn-danger',
                method: :delete, data: { confirm: 'Are you sure?' } %>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-sm-4"></div>
    </div>

  </div>
</section>