config/routes.rb
Rails.application.routes.draw do
  root   'radio_stations#top'

  get    '/signup',   to: 'users#new'

  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  delete '/signout',  to: 'sessions#destroy'

  resources :radio_stations do
    collection do
      post :confirm
    end
  end

  resources :users, except: [:index, :new] do
    collection do
      post :confirm
    end
    resources :favorite_stations, only: [:index]
  end

  resources :favorites, only: %i[ create destroy ]

  resources :account_activations, only: [:edit]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <% site_name = 'Favtune' %>
  <title><%= content_for?(:html_title) ? yield(:html_title) + " - #{site_name}" : "#{site_name}" %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="" style="">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light affix" id="mainNav">
      <div class="container">
        <%= link_to "Favtune", root_path, class: 'navbar-brand nav-logo' %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <% if signed_in? %>
            <li class="nav-item">
              <%= link_to "Shared stations", radio_stations_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Post station", new_radio_station_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Your profile", user_path(current_user.id), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", signout_path(current_user.id), class: 'nav-link', method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in", signin_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", signup_path, class: 'nav-link' %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <!-- HOME -->
  <%= yield %>
  <!--/HOME -->
  <footer>
    <div id="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div id="footer-copyrights">
              <p>Copyrights &copy; 2018 All Rights Reserved by Favtune. </p>
              <p>Top template by
                <%= link_to(
                  %(ThemeWagon - Businessbox),
                  %(https://themewagon.com/themes/multi-page-bootstrap-4-business-template/),
                  rel: 'noopener', target: '_blank'
                ) %>
              | Top photo by
                <%= link_to(
                  %(neil godding on Unsplash),
                  %(https://unsplash.com/photos/NMbZ7QM3XWM),
                  rel: 'noopener', target: '_blank'
                ) %>
              | Top effect photo on
                <%= link_to(
                  %(ThemeWagon - Startup),
                  %(https://themewagon.com/themes/bootstrap-html5-multipurpose-business-template/),
                  rel: 'noopener', target: '_blank'
                ) %>
              </p>
              <p>Sign up, Sign in and Users edit template by
                <%= link_to(
                  %(Start Bootstrap - SB Admin),
                  %(https://startbootstrap.com/template-overviews/sb-admin/),
                  rel: 'noopener', target: '_blank'
                ) %>
              | Stations new, edit and Users show template by
                <%= link_to(
                  %(Start Bootstrap - Agency),
                  %(https://startbootstrap.com/template-overviews/agency/),
                  rel: 'noopener', target: '_blank'
                ) %>
              </p>
              <p>Stations index template by
                <%= link_to(
                  %(ThemeWagon - Edulogy),
                  %(https://themewagon.com/themes/free-html-education-template-multi-page/),
                  rel: 'noopener', target: '_blank'
                ) %>
              | Stations show template by
                <%= link_to(
                  %(ThemeWagon - B-Hero),
                  %(https://themewagon.com/themes/free-bootstrap-4-business-website-template/),
                  rel: 'noopener', target: '_blank'
                ) %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div>
      <a id="back-to-top" class="btn btn-sm btn-green btn-back-to-top hidden-sm hidden-xs" title="home" role="button">
        <i class="fa fa-angle-up"></i>
      </a>
    </div>
  </footer>
</body>
</html>